services:
    postgres:
        image: postgres:latest
        container_name: jobber-postgres
        environment:
            POSTGRES_DB: jobber
            POSTGRES_USER: jobber
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql
        restart: unless-stopped
