services:
    postgres:
        image: postgres:latest
        container_name: jobber-postgres
        environment:
            POSTGRES_DB: jobber
            POSTGRES_USER: jobber
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql
        restart: unless-stopped
        networks:
            - jobber-network

    jobber:
        build: .
        container_name: jobber
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            DB_HOST: postgres
        ports:
            - "80:80"
        volumes:
            - ./jobber.log:/jobber.log
        depends_on:
            - postgres
        restart: unless-stopped
        networks:
            - jobber-network

networks:
    jobber-network:
        driver: bridge
